--CONSULTA UTILIZANDO JOINS
SELECT 
	 F.CD_FUNCIONARIO
	,F.NM_FUNCIONARIO 
	,DT_NASCIMENTO 
	,D.NM_DEPTO
FROM DB_FUNCIONARIO F
INNER JOIN DB_DEPTO D
	ON (D.CD_DEPTO = F.CD_DEPTO)
INNER JOIN DB_END_FUNC E
	ON (E.CD_FUNCIONARIO = F.CD_FUNCIONARIO)
INNER JOIN DB_LOGRADOURO L 
	ON (L.CD_LOGRADOURO = E.CD_LOGRADOURO)
INNER JOIN DB_BAIRRO B 
	ON (B.CD_BAIRRO = L.CD_BAIRRO)
WHERE B.NM_BAIRRO = 'Vila Mariana';

SELECT 
	C.NM_CLIENTE,
    L.NM_LOGRADOURO, 
    L.NR_CEP
FROM DB_CLIENTE C
INNER JOIN DB_END_CLI E
	ON (E.NR_CLIENTE  = C.NR_CLIENTE)
INNER JOIN DB_LOGRADOURO L 
	ON (L.CD_LOGRADOURO = E.CD_LOGRADOURO_CLI)
INNER JOIN DB_BAIRRO B 
	ON (B.CD_BAIRRO = L.CD_BAIRRO)
WHERE B.NM_BAIRRO = 'Saúde'
AND C.QT_ESTRELAS >= 4;
	
--CONSULTA UTILIZANDO JOIN E FILTROS
SELECT
	*
FROM DB_CLIENTE
WHERE QT_ESTRELAS >= 4;

SELECT 
	*
FROM DB_CLIENTE dc 
WHERE QT_ESTRELAS >= 3
AND VL_MEDIO_COMPRA > 100;

SELECT 
	NM_CLIENTE,
	QT_ESTRELAS
FROM DB_CLIENTE
WHERE VL_MEDIO_COMPRA > 100;

SELECT
	*
FROM DB_PRODUTO
WHERE VL_UNITARIO > 30;

--DESAFIO
SELECT
	 EXTRACT(MONTH FROM DT_PEDIDO) MESES_PEDIDO
	,SUM(VL_TOT_PEDIDO)
FROM DB_PEDIDO
WHERE EXTRACT(YEAR FROM DT_PEDIDO) = 2019
GROUP BY EXTRACT(MONTH FROM DT_PEDIDO)
order by meses_pedido;

SELECT EXTRACT(MONTH FROM DT_PEDIDO) MESES_PEDIDO, 
       SUM(VL_TOT_PEDIDO) VALOR_TOTAL,
       COUNT(NR_PEDIDO) QTD_PEDIDOS
FROM DB_PEDIDO
WHERE EXTRACT(YEAR FROM DT_PEDIDO)=2019
GROUP BY EXTRACT(MONTH FROM DT_PEDIDO)
ORDER BY MESES_PEDIDO;