ALTER TABLE ITEM_PRODUTO ADD TIPO_MEDIDA VARCHAR2(30);

ALTER TABLE ITEM_PRODUTO ADD CONSTRAINT CS_TIPOS CHECK (TIPO_MEDIDA IN ('LITRO','KILO','UNIDADE'));

SELECT CONSTRAINT_TYPE, CONSTRAINT_NAME, TABLE_NAME, SEARCH_CONDITION FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('ITEM_PRODUTO','MATERIA_PRIMA','PRODUTO','CATEGORIA');

CREATE SEQUENCE SEQ_CATEG START WITH 1 INCREMENT BY 1;

INSERT INTO CATEGORIA (COD_CATEGORIA,CATEGORIA) 
	VALUES (SEQ_CATEG.NEXTVAL, 'DOCE');
INSERT INTO CATEGORIA (COD_CATEGORIA,CATEGORIA) 
	VALUES (SEQ_CATEG.NEXTVAL, 'BEBIDA');
INSERT INTO CATEGORIA (COD_CATEGORIA,CATEGORIA) 
	VALUES (SEQ_CATEG.NEXTVAL, 'CONGELADO');
	
SELECT * FROM CATEGORIA;