-- INSERT
CREATE TABLE CIENTISTA (
	CODIGO NUMBER(4,0) PRIMARY KEY,
	NOME VARCHAR2(50) NOT NULL, 
	DT_NASC DATE,
	SEXO CHAR(1)
);

ALTER TABLE CIENTISTA ADD CONSTRAINT CS_SEX CHECK (SEXO IN ('M', 'F'));
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/RRRR';

CREATE SEQUENCE SEQ_CIENTISTA START WITH 1010 INCREMENT BY 1;

INSERT INTO CIENTISTA (CODIGO,NOME,DT_NASC,SEXO) VALUES (SEQ_CIENTISTA.NEXTVAL, 'STEPHEN HAWKING', '08/01/1942','M');
INSERT INTO CIENTISTA (CODIGO,NOME,DT_NASC,SEXO) VALUES (SEQ_CIENTISTA.NEXTVAL, 'ALBERT EINSTEIN', '14/03/1879','M');
INSERT INTO CIENTISTA (CODIGO,NOME,DT_NASC,SEXO) VALUES (SEQ_CIENTISTA.NEXTVAL, 'ISAAC NEWTON', '04/01/1643','M');
INSERT INTO CIENTISTA (CODIGO,NOME,DT_NASC,SEXO) VALUES (SEQ_CIENTISTA.NEXTVAL, 'GALILEU GALILEI', '15/02/1564','M');
INSERT INTO CIENTISTA (CODIGO,NOME,DT_NASC,SEXO) VALUES (SEQ_CIENTISTA.NEXTVAL, 'NICOLAU COPERNICO', '19/01/1473','M');

SELECT * FROM CIENTISTA;

CREATE TABLE CLIENTE (
	CODIGO NUMBER(4,0) PRIMARY KEY,
	NOME VARCHAR2(50) NOT NULL
);

INSERT INTO CLIENTE
SELECT CODIGO,NOME FROM CIENTISTA;

SELECT * FROM CLIENTE;

-- UPDATE 
ALTER TABLE CIENTISTA ADD DT_OBTO DATE;

UPDATE CIENTISTA SET DT_OBTO = '14/03/2018' WHERE NOME = 'STEPHEN HAWKING';
UPDATE CIENTISTA SET DT_OBTO = '18/04/1955' WHERE NOME = 'ALBERT EINSTEIN';
UPDATE CIENTISTA SET DT_OBTO = '31/03/1727' WHERE NOME = 'ISAAC NEWTON';
UPDATE CIENTISTA SET DT_OBTO = '08/01/1642' WHERE NOME = 'GALILEU GALILEI';
UPDATE CIENTISTA SET DT_OBTO = '24/05/1543' WHERE NOME = 'NICOLAU COPERNICO';

UPDATE CIENTISTA SET NOME = 'ALBERT' WHERE CODIGO = 1011;
UPDATE CIENTISTA SET NOME = 'ISAAC' WHERE CODIGO = 1012;

ALTER TABLE CLIENTE ADD DT_NASC DATE;

UPDATE CLIENTE A SET DT_NASC = (SELECT DT_NASC FROM CIENTISTA 
									WHERE CODIGO = A.CODIGO);
									
-- DELETE
DELETE FROM CIENTISTA WHERE TO_CHAR(DT_NASC, 'MM') <> '02';

DELETE FROM CLIENTE A
WHERE NOT EXISTS (SELECT 1 FROM CIENTISTA 
					WHERE CODIGO = A.CODIGO);