-- CONSULTA SIMPLES;
SELECT NM_FUNCIONARIO, DT_CADASTRAMENTO FROM DB_FUNCIONARIO;

SELECT 
	 NM_FUNCIONARIO
	,VL_SALARIO_BRUTO
	,VL_SALARIO_BRUTO  + VL_SALARIO_BRUTO * 0.05 AS "PROJECAO 5%"
	,VL_SALARIO_BRUTO + VL_SALARIO_BRUTO * 0.08 AS "PROJECAO 8%"
FROM DB_FUNCIONARIO;

SELECT
	 NM_CLIENTE
	,QT_ESTRELAS
FROM DB_CLIENTE;

SELECT 
	 DS_PRODUTO
	,VL_UNITARIO
FROM DB_PRODUTO;

-- CONSULTA COM CONDIÇÕES
SELECT 
	* 
FROM DB_CLIENTE
WHERE QT_ESTRELAS >= 4;

SELECT 
	* 
FROM DB_CLIENTE
WHERE QT_ESTRELAS >= 3 AND VL_MEDIO_COMPRA >= 100.00;

SELECT 
	*
FROM DB_PRODUTO
WHERE VL_UNITARIO >= 30;

-- DESAFIO
SELECT 
	*
FROM DB_PEDIDO dp 
WHERE EXTRACT(MONTH FROM DT_PEDIDO) <= '3'
AND EXTRACT(YEAR FROM DT_PEDIDO) = EXTRACT(YEAR FROM CURRENT_DATE)-1;

SELECT * FROM DB_FUNCIONARIO df 
WHERE EXTRACT(MONTH FROM DT_CADASTRAMENTO) IN ('11','12');

SELECT 
	*
FROM DB_PEDIDO dp 
WHERE EXTRACT(YEAR FROM DT_PEDIDO) = '2018'